### ISSUE TITLE
Incorrect Link

### ISSUE THREAD

**Issue by murilomagalhaes** [Ditectrev/Professional-Scrum-Developer-I-PSD-I-Practice-Exams-Questions-Answers#2]
The link to the Udemy course is broken. It says that the course with the id of 4266138 is not available.

**Comment by danieldanielecki** [comment]
Udemy has (hopefully, temporarily) disabled the course for unknown reasons. I'm clarifying :)

**Comment by danieldanielecki** [comment]
@murilomagalhaes, the course has been [reuploaded](https://www.udemy.com/course/professional-scrum-developer-i-psd-i-practice-exams/?referralCode=E1E5C69CF22100D112DD). We had an unfortunate situation with Udemy to due using one of the forbidden keywords according to their rules :(
