### ISSUE TITLE
Wrong answer on question "What are three ways Scrum promotes self-organization?"

### ISSUE THREAD

**Issue by intoinside** [Ditectrev/Professional-Scrum-Developer-I-PSD-I-Practice-Exams-Questions-Answers#4]
On question "What are three ways Scrum promotes self-organization?", correct answer are:
By the Development Team deciding what work to do in a Sprint.
By removing titles for Development Team members.
By being a lightweight framework.

Currently are selected only two of them

**Comment by danieldanielecki** [comment]
@intoinside, thanks for being sharp on this!

Fixed in https://github.com/Ditectrev/Professional-Scrum-Developer-I-PSD-I-Practice-Exams-Questions-Answers/commit/bfc75184b246255b420083f74c621198af1dcf67
